version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - yum update -y
      - yum install -y docker
      - dockerd > /dev/null 2>&1 &
      - echo Installing source dependencies...
      - pip install -r requirements.txt
      - echo Installing Amazon Inspector SBOM Generator...
      - curl -Lo inspector-sbomgen.zip https://amazon-inspector-sbomgen.s3.amazonaws.com/latest/linux/amd64/inspector-sbomgen.zip
      - unzip inspector-sbomgen.zip
      - chmod +x inspector-sbomgen-1.5.5/linux/amd64/inspector-sbomgen
      - mv inspector-sbomgen-1.5.5/linux/amd64/inspector-sbomgen .
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 116981763358.dkr.ecr.ca-central-1.amazonaws.com
      - REPOSITORY_URI=116981763358.dkr.ecr.ca-central-1.amazonaws.com/sharma3
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
  commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Generating SBOM for the Docker image...
    - ./inspector-sbomgen container --image $REPOSITORY_URI:latest -o sbom.json
    - echo Scanning the SBOM with Amazon Inspector...
    - aws inspector2 create-findings-report --report-type SBOM --resource-arn $REPOSITORY_URI:latest --report-format JSON --s3-destination bucketName=codepipeline-ca-central-1-179121243595
artifacts:
  files:
    - app.py
    - Dockerfile
    - requirements.txt
